### ISSUE TITLE
Evaluating impact on web dev workflows. Might require a custom server during dev?

### ISSUE THREAD

**Issue by sethladd** [lrhn/dep-pkgspec#12]
I love packagespec... getting rid of symlinks is fantastic.

My understanding is that with packages.txt (or whatever it is called), we no longer need to put a `packages/` dir into a project.

Thinking about the web developer workflow, though. Do we want to support a case where a developer can use any HTTP server to serve their Dart web app? If so, that web server will need to know how to turn a request for `packages/foo/resource.css` into a location on disk specified by the packages.txt file.

Can we have it both ways:
- No symlinks
- A web development workflow that allows for an arbitrary HTTP server to serve the app during development.
- No build steps during development.

I think this implies that the packages/ dir must physically be present under the web/ with all packages's lib directories copied into web/packages/ such that the HTTP server can easily serve those files.

Thoughts?

**Comment by alan-knight** [comment]
Yes, I think we could do this, if
- there's a packages directory at the top level. It would presumably need to have symlinks, or else copy all the files in. But we wouldn't need the extra symlink to packages in every directory.
- we can assume the server is serving from the root. That is http://domain.com/, no additional path
- we translate package: URLs into /packages/... , rather than being relative.

Avoiding the need for absolute URLs is part of why we have the symlinks in each directory. But it might be reasonable as a way of saying you can use an arbitrary web server.

**Comment by lrhn** [comment]
If you want a simple HTTP server to serve a specific single directory as your application, then you need your packages to be in that directory. No news there. Symbolic links might actually work better for that use-case, because you want something that is entirely file-system based. There should still only be the one packages-directory with symlinks for that particular purpose, and you can remove it again when the HTTP server shuts down.

If you can configure the server to dynamically map directories, then you might be able to load the packages.map file and use that as part as the server configuration, dynamically mapping /packages/foo/x/y/z into the somethinglocal/x/y/z where foo=somethinglocal is in the packages.map file. 

That's server-specific. I'm sure the Pub serve command can do it.

**Comment by sethladd** [comment]
We have to come up with a solution that doesn't require `pub serve`. I'm perfectly fine with making a physical copy of my package dependencies into a packages/ dir right inside of web/. As mentioned, this means that `package:` needs to be turned into `/packages/`. Is that sufficient?

**Comment by alan-knight** [comment]
You can't send package: to arbitrary web server. You would have to write it in your application as an http URL, e.g. /packages/foo/..., or use the proposed Uri.fromPackage

That's sufficient if you're serving a single application from the root of your domain. It's not sufficient if you have multiple applications and you don't have control of the root, or the applications might have different versions of particular applications. So if my app is rooted at http://hostingservice.com/myproject/index.html, and I can't put URLs at the top level of hostingservice.com, it's not enough.

It might be enough if you can tell the user that you must explicitly prefix your URLS. So if you want to use a web server that doesn't know about Dart package conventions, what you must do is write your references differently. Where you might have written 'packages/foo/images/foo.jpg' you must now write '$prefix/foo/images/foo.jpg' and define const prefix = 'http://hostingservice.com/myproject/packages/';

These seem like the sort of issues that Bob and Natalie would have wrestled with extensively in the past.

**Comment by sethladd** [comment]
Good point: absolute URIs suck. Let's avoid that.

One thing that might be helpful: HTML's `<base>` tag in `<head>`. That's a potentially easier way to set a prefix.

I'd like to know how Polymer will deal with the lack of packages/ directories and symlinks.

cc @jakemac53

**Comment by sethladd** [comment]
I wonder if this is the right forum to talk about this? It's not really a "bug" on the proposal.

**Comment by jakemac53** [comment]
Polymer already requires that all files point at the same packages directory (today a symlink). We currently enforce that this is the one that appears at the same level as the entry point, but it doesn't really matter to us where it comes from.

In general getting rid of symlinks should make things way easier for polymer users, one of the most common issues we have today is multiple copies of polymer getting pulled in because of people pointing at different packages symlinks.

**Comment by sethladd** [comment]
@jakemac53 do polymer.dart developers use HTML imports? if so, what does the URL look like?

**Comment by jakemac53** [comment]
Yes html imports are still used and are the primary cause of issues with respect to symlinks. With the new @HtmlImport we allow `package:` urls which eliminate this issue, but many people haven't migrated to this yet, and some never will unless we completely dropped support for hardcoded html imports.

The rules today for properly writing html imports are somewhat complicated and depend on what directory you are in, there is some discussion on that [here](https://www.dartlang.org/polymer/app-directories.html#into-a-non-dart-file-under-lib).

**Comment by munificent** [comment]
> One thing that might be helpful: HTML's <base> tag in <head>. That's a potentially easier way to set a prefix.

I recall dimly from my initial research before we created `pub serve` that `<base>` didn't turn out to be helpful.

Is your concern about developers using Dartium? If we're willing to ask them to use a custom-built browser from the Dart team, it doesn't seem unreasonable to me to ask them to also use a server from us.

**Comment by sethladd** [comment]
Closing as this isn't relevant to the DEP.
