### ISSUE TITLE
Search parents for `packages` dir?

### ISSUE THREAD

**Issue by eernstg** [lrhn/dep-pkgspec#17]
The following was discussed on a [package_config] thread, and it was recommended that I should create this issue to put it in the right context. It is concerned with the rules for resolving 'package:' URIs, bullet 3, where the recursive parent directory search is mentioned. Here was my response to the fact that this rule does not include a similar search for a `packages` directory (such a directory is only search in the current directory, not parents):

If it is OK to check the parent directory for a `.packages` file then we might as well check for `packages` as well.

> A concrete example where I've seen the need: When `pub build` creates `packages` symlinks on the source side (that as, the file tree under `my_package/web`, or `my_package/X` where X is the final argument to `pub build ..`), it creates them in all subdirectories. On the target side (my_package/build/web etc.) there are no symlinks (such that the build file tree can be copied without breaking), and for space economy only the topmost 'packages' directory is created. This means that Dart code may run on the source side and break on the target side, because the former has a local `packages` directory (link) and the latter doesn't (so the latter needs a --package-root argument).
> 
> In both cases, the question is whether we will (ever? too often?) use an unintended `.packages` file (or `packages` directory), because there is none (of the right kind), but somewhere, too far up the path to the root directory, we find some arbitrary different thing that has the same name. 
> 
> This can be a security problem, if an attacker gets a chance to create a rogue `.packages` file in a suitable directory on an important web server, and the above-mentioned glitch causes a search for `.packages` in superdirs that skips over the `build/<something>/packages` dir and finds the rogue file.

**Comment by eernstg** [comment]
Carrying over Lasse's response to this:

> We could try looking for packages directories in the parent path. It might be convenient at times.
> One of the reason for why I have chosen not to do that is as a subtle encouragement to switch to a .packages file.
> 
> Eventually pub will stop creating packages/ directories, and then that discrepancy will disappear.
> 
> You won't find a .packages file served by a web server since the parent-path search is only performed on file:-locations. If the web-server is running server-side Dart and you get to place a file in its program path, you probably have bigger problems. Not to say that it's not highly exploitable, so when running a server, you might be encouraged to use the --packages command line parameter to disable the search.

**Comment by eernstg** [comment]
The encouragement to switch to `.packages` could be achieved if tools were to print a message about it, I don't think treating `packages` differently from `.packages` will have any effect at all, except when it makes something break, at which point it probably causes more confusion than persuasion. ;)

The search for `packages` can then be deprecated now and later eliminated entirely.

For the security problem, I wasn't thinking about a process whereby a library is fetched from a web server, I was thinking about the local search according to these rules on any host (presumably an important deployment target is the most interesting case here). If such a search finds a rogue `.packages` file in a superdir and skips `build/<something>/packages` because of the lack of a `build/<something>/<moredirs>/packages` directory, then they would be able to reinterpret the meaning of imports ad libitum. Surely that could be a security problem.

**Comment by lrhn** [comment]
True, a malicious .packages file can cause a complete arbitrary-code exec exploit.
That's true whether we look for packages directories or not, because we might not find any.

When the pub CL lands, we will create a .packages file at the same place where we place the top-most packages/ directory. At that point, any attempt to run from a sub-directory should stop at the .packages file. Running from a sub-directory _should_ find the .packages file, not the lower-level packages directory, so running from build/something/moredirs/ should find the .packages file in build/something, not the packages directory in build/something/moredirs. That means that we can't just look for a packages directory at the same time we look for .packages files.

That means that for existing directories with only packages-dirs and no .packages file, a reachable .packages file is a problem.
Maybe we should stop the search if we see a pubspec-yaml file, and assume that that is the root of a package. That's more complication, and won't help on a deployed application.

**Comment by lrhn** [comment]
There is no plan to change this for now.
